version: "3"

services:
  mongodb:
    container_name: mongodb
    volumes:
      - "db-data:/opt/mongo/data"
    image: mongo:3.4.2
    hostname: mongodb
    ports:
      - "27017:27017"
    networks:
          - backend

  configserver:
    image: eureka
    command: ["./wait-for-it.sh", "-t", "0", "mongodb:27017", "--", "java","-Djava.security.egd=file:/dev/./urandom","-jar","/configserver.jar"]
    hostname: configserver
    depends_on:
      - mongodb
    volumes:
      - ./configserver:/app
    ports:
      - "7007:7007"
    networks:
      - backend

  eureka:
    image: eureka
    command: ["./wait-for-it.sh", "-t", "0", "configserver:9000", "--", "java","-Djava.security.egd=file:/dev/./urandom","-jar","/eureka.jar"]
    depends_on:
    - configserver
    volumes:
     - ./eureka:/app
    ports:
      - "8761:8761"
    networks:
      - backend

#  apigateway:
#    image: apigateway
#    depends_on:
#    - eureka
#    ports:
#    - "8675:8675"
#
#  shipping:
#    image: shipping
#    depends_on:
#    - eureka
#    ports:
#    - "7923:7923"
#
#  price:
#    image: price
#    depends_on:
#    - eureka
#    ports:
#    - "23405:23405"
#
#  invoice:
#    image: invoice
#    depends_on:
#    - eureka
#    ports:
#    - "11223:11223"
#
#  creditcard:
#    image: creditcard
#    depends_on:
#    - eureka
#    ports:
#    - "44444:44444"
#
#  cart:
#    image: cart
#    depends_on:
#    - eureka
#    ports:
#    - "22222:22222"
#
#  address:
#    image: address
#    depends_on:
#    - eureka
#    ports:
#    - "55555:55555"
#
#  product:
#    image: product
#    depends_on:
#    - eureka
#    ports:
#    - "12894:12894"
#
#  zuulgateway:
#    image: zuulgateway
#    depends_on:
#     - eureka
#    ports:
#    - "8723:8723"

volumes:
  db-data:

networks:
  backend:
  frontend: