version: '2'

services:

  mongodb:
    container_name: mongodb
    image: mongo:3.4.2
    hostname: mongodb
    command: mongod --smallfiles
    ports:
      - "12565:12565"

  eureka:
    image: eureka
    depends_on:
      - mongodb
    ports:
      - "8761:8761"

  apigateway:
    image: apigateway
    depends_on:
    - eureka
    ports:
    - "8675:8675"

  shipping:
    image: shipping
    depends_on:
    - eureka
    ports:
    - "7923:7923"

  price:
    image: price
    depends_on:
    - eureka
    ports:
    - "23405:23405"

  invoice:
    image: invoice
    depends_on:
    - eureka
    ports:
    - "11223:11223"

  creditcard:
    image: creditcard
    depends_on:
    - eureka
    ports:
    - "44444:44444"

  cart:
    image: cart
    depends_on:
    - eureka
    ports:
    - "23405:23405"

  address:
    image: address
    depends_on:
    - eureka
    ports:
    - "23405:23405"

  product:
    image: product
    depends_on:
    - eureka
    ports:
    - "12894:12894"

  zuulgateway:
    image: zuulgateway
    depends_on:
     - eureka
    ports:
    - "8723:8723"