server:
  port: 8723

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

spring:
  application:
    name: zuulgateway
  data:
    mongodb:
     host: mongodb

#server.port=8723
#spring.application.name=zuul